import type { Analysis, SolveResult, SystemDesign } from '@/engine';
import { fmtDuration, fmtPct, fmtRps } from './format';

/** A plain-markdown snapshot of the design and its analytical solution. */
export function buildReport(
  design: SystemDesign,
  result: SolveResult,
  analysis: Analysis,
): string {
  const sc = design.sim.scenario;
  const load =
    sc.mode === 'users'
      ? `${sc.users?.toLocaleString()} users, ${sc.thinkTimeSec ?? 1}s think time`
      : `${fmtRps(sc.targetRps)} target`;

  const lines: string[] = [];
  lines.push(`# ${design.name}`, '');
  if (design.description) lines.push(design.description, '');
  lines.push(
    `- **Scenario:** ${sc.kind}, ${load}, ${sc.durationSec}s`,
    `- **Offered / served:** ${fmtRps(result.system.offeredRps)} / ${fmtRps(result.system.servedRps)}`,
    `- **End-to-end p50 / p95 / p99:** ${fmtDuration(result.system.latency.p50)} / ${fmtDuration(
      result.system.latency.p95,
    )} / ${fmtDuration(result.system.latency.p99)}`,
    `- **Success rate:** ${fmtPct(result.system.successRate)}`,
    `- **Health:** ${result.system.healthy ? 'healthy' : 'degraded'}`,
    '',
    '## Components',
    '',
    '| Component | Type | ρ | Arrivals | p99 | Drop | Error |',
    '| --- | --- | ---: | ---: | ---: | ---: | ---: |',
  );

  for (const n of design.nodes) {
    const m = result.perNode[n.id]?.metrics;
    if (!m) continue;
    lines.push(
      `| ${n.label ?? n.type} | ${n.type} | ${m.rho.toFixed(2)} | ${fmtRps(m.arrivalRate)} | ${fmtDuration(
        m.latency.p99,
      )} | ${fmtPct(m.dropRate)} | ${fmtPct(m.errorRate)} |`,
    );
  }

  lines.push('', '## Bottleneck audit', '');
  if (analysis.healthy) {
    lines.push('No component is close to its limit.');
  } else {
    lines.push(analysis.summary, '');
    for (const b of analysis.bottlenecks) {
      lines.push(`- **${b.label}** — ${b.reason}`);
    }
    if (analysis.fixes.length) {
      lines.push('', '### Suggested fixes', '');
      for (const f of analysis.fixes) {
        lines.push(
          `- ${f.clears ? '**clears**' : 'helps'} — ${f.label} (→ ${fmtPct(f.projectedSuccess)} success)`,
        );
      }
    }
  }

  lines.push('', '---', '', '_Generated by Breakpoint._');
  return lines.join('\n');
}
